version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: cafeOps
      POSTGRES_USER: prince
      POSTGRES_PASSWORD: 1234567890

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: spring_backend
    restart: unless-stopped

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cafeOps
      SPRING_DATASOURCE_USERNAME: prince
      SPRING_DATASOURCE_PASSWORD: 1234567890

    ports:
      - "8082:8082"

  ml:
    build:
      context: ./model
      dockerfile: Dockerfile

    container_name: ml_service
    restart: unless-stopped

    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: react_frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:5173"

    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data: